name: Build-Deploy-AppCode
on:
  workflow_dispatch:  
    inputs:
      run_id:
        description: Build ID to Deploy
        required: false
        default: null
      mode:
        description: environment to run against - dev or staging
        required: true
        default: dev
        type: choice
        options:
        - dev
        - stg
#  pull_request:
  push:
env:  
  RUN_ID: ${{ github.event.inputs.run_id }}
  GITHUB_RUN_ID: ${{ github.run_id }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
jobs:  
  Build-AppCode:
    runs-on: ais-windows
    steps:  
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      - name: Building AppCode
        shell: powershell
        working-directory: C:\Users\osadmin\actions-runner\_work
        run: |  
              Import-Module 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
              Enter-VsDevShell df0f207e
              cd '.\app-service-web-dotnet-get-started\app-service-web-dotnet-get-started'
              MSBuild
              #MSBuild /p:'configuration="release";platform="any cpu";WebPublishMethod=Package;PackageFileName="package.zip";PackageAsSingleFile=true;DeployOnBuild=true;DeployTarget=Package'
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: checkov-output
      #     path: results.sarif
           